# Data Manipulation Studio

For this studio, we will revisit our California farmers looking for advice on growing pumpkins and the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [1]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np

baltimore = pd.read_csv('C:/Users/JChou/Desktop/Women+/17. Data Manipulation/17.3 Studio/dataset/baltimore_9-24-2016_9-30-2017.csv')
boston = pd.read_csv('C:/Users/JChou/Desktop/Women+/17. Data Manipulation/17.3 Studio/dataset/boston_9-24-2016_9-30-2017.csv')
new_york = pd.read_csv('C:/Users/JChou/Desktop/Women+/17. Data Manipulation/17.3 Studio/dataset/new-york_9-24-2016_9-30-2017.csv')
philadelphia = pd.read_csv('C:/Users/JChou/Desktop/Women+/17. Data Manipulation/17.3 Studio/dataset/philadelphia_9-24-2016_9-30-2017.csv')

## Clean Your Data

In the last lesson, we cleaned the data to related to San Francisco. Pull up your notebook from the last lesson and use your cleaning skills to clean the dataframes as necessary.

In [2]:
# Clean your data here!
for col in baltimore.columns:
    pct_missing = np.mean(baltimore[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
print('\n')
for col in boston.columns:
    pct_missing = np.mean(boston[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
print('\n')
for col in new_york.columns:
    pct_missing = np.mean(new_york[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
print('\n')
for col in philadelphia.columns:
    pct_missing = np.mean(philadelphia[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))# Clean your data here!
for col in baltimore.columns:
    pct_missing = np.mean(baltimore[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
print('\n')
for col in boston.columns:
    pct_missing = np.mean(boston[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
print('\n')
for col in new_york.columns:
    pct_missing = np.mean(new_york[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
print('\n')
for col in philadelphia.columns:
    pct_missing = np.mean(philadelphia[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
baltimore_dropped = baltimore.drop(['Commodity Name', 'Type', 'Grade', 'Origin District', 'Environment', 'Quality','Condition','Appearance','Storage','Crop','Repack','Trans Mode','Mostly Low', 'Mostly High'], axis=1)
boston_dropped = boston.drop(['Commodity Name', 'Type', 'Grade', 'Origin District', 'Environment', 'Quality','Condition','Appearance','Storage','Crop','Repack','Trans Mode','Mostly Low', 'Mostly High'], axis=1)
new_york_dropped = new_york.drop(['Commodity Name', 'Type', 'Grade', 'Origin District', 'Environment', 'Quality','Condition','Appearance','Storage','Crop','Repack','Trans Mode','Mostly Low', 'Mostly High'], axis=1)
philadelphia_dropped = philadelphia.drop(['Commodity Name', 'Type', 'Grade', 'Origin District', 'Environment', 'Quality','Condition','Appearance','Storage','Crop','Repack','Trans Mode','Mostly Low', 'Mostly High'], axis=1)

Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 1.0%
Sub Variety - 84.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 3.0%
Origin District - 100.0%
Item Size - 16.0%
Color - 80.0%
Environment - 100.0%
Unit of Sale - 84.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%


Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 0.0%
Sub Variety - 92.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 0.0%
Origin District - 81.0%
Item Size - 1.0%
Color - 14.0%
Environment - 100.0%
Unit of Sale - 87.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%


Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 0.0%
Sub Variety - 84.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 0.0%
Origin District - 87.0%
Item Size - 7.0%
Color - 81.0%
Environment - 100.0%
Unit of Sale - 78.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%


Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 0.0%
Sub Variety - 79.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 0.0%
Origin District - 100.0%
Item Size - 21.0%
Color - 100.0%
Environment - 100.0%
Unit of Sale - 81.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%
Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 1.0%
Sub Variety - 84.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 3.0%
Origin District - 100.0%
Item Size - 16.0%
Color - 80.0%
Environment - 100.0%
Unit of Sale - 84.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%


Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 0.0%
Sub Variety - 92.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 0.0%
Origin District - 81.0%
Item Size - 1.0%
Color - 14.0%
Environment - 100.0%
Unit of Sale - 87.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%


Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 0.0%
Sub Variety - 84.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 0.0%
Origin District - 87.0%
Item Size - 7.0%
Color - 81.0%
Environment - 100.0%
Unit of Sale - 78.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%


Commodity Name - 0.0%
City Name - 0.0%
Type - 100.0%
Package - 0.0%
Variety - 0.0%
Sub Variety - 79.0%
Grade - 100.0%
Date - 0.0%
Low Price - 0.0%
High Price - 0.0%
Mostly Low - 0.0%
Mostly High - 0.0%
Origin - 0.0%
Origin District - 100.0%
Item Size - 21.0%
Color - 100.0%
Environment - 100.0%
Unit of Sale - 81.0%
Quality - 100.0%
Condition - 100.0%
Appearance - 100.0%
Storage - 100.0%
Crop - 100.0%
Repack - 0.0%
Trans Mode - 100.0%

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [3]:
# Combine the four dataframes into one!
northeast = pd.concat([baltimore_dropped, boston_dropped, new_york_dropped, philadelphia_dropped])
northeast

,City Name,Package,Variety,Sub Variety,Date,Low Price,High Price,Origin,Item Size,Color,Unit of Sale
0,BALTIMORE,24 inch bins,NaN,NaN,04/29/2017,270,280.0,NaN,lge,NaN,NaN
1,BALTIMORE,24 inch bins,NaN,NaN,05/06/2017,270,280.0,NaN,lge,NaN,NaN
2,BALTIMORE,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,DELAWARE,med,NaN,NaN
3,BALTIMORE,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,VIRGINIA,med,NaN,NaN
4,BALTIMORE,24 inch bins,HOWDEN TYPE,NaN,11/05/2016,90,100.0,MARYLAND,lge,NaN,NaN
5,BALTIMORE,24 inch bins,HOWDEN TYPE,NaN,11/12/2016,90,100.0,MARYLAND,lge,NaN,NaN
6,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,170.0,MARYLAND,med,NaN,NaN
7,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,PENNSYLVANIA,lge,NaN,NaN
8,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/01/2016,160,170.0,MARYLAND,med,NaN,NaN
9,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/01/2016,160,160.0,PENNSYLVANIA,lge,NaN,NaN
10,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/08/2016,160,170.0,MARYLAND,med,NaN,NaN
11,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/08/2016,160,160.0,PENNSYLVANIA,lge,NaN,NaN
12,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/15/2016,150,160.0,MARYLAND,lge,NaN,NaN
13,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/15/2016,150,170.0,MARYLAND,med,NaN,NaN
14,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/22/2016,150,160.0,MARYLAND,lge,NaN,NaN
15,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/22/2016,140,160.0,MARYLAND,med,NaN,NaN
16,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/29/2016,100,160.0,MARYLAND,lge,NaN,NaN
17,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/29/2016,130,160.0,MARYLAND,med,NaN,NaN
18,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,10/29/2016,130,130.0,MARYLAND,sml,NaN,NaN
19,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,11/05/2016,120,130.0,MARYLAND,xlge,NaN,NaN
20,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,11/05/2016,100,130.0,MARYLAND,lge,NaN,NaN
21,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,11/05/2016,90,100.0,MARYLAND,med,NaN,NaN
22,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,11/12/2016,100,120.0,MARYLAND,lge,NaN,NaN
23,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,09/16/2017,160,160.0,MARYLAND,med-lge,ORANGE,NaN
24,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,09/23/2017,160,160.0,MARYLAND,med-lge,ORANGE,NaN
25,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,09/30/2017,150,160.0,MARYLAND,lge,ORANGE,NaN
26,BALTIMORE,36 inch bins,HOWDEN TYPE,NaN,09/30/2017,150,160.0,MARYLAND,med-lge,ORANGE,NaN
27,BALTIMORE,24 inch bins,HOWDEN WHITE TYPE,NaN,09/23/2017,160,180.0,MARYLAND,med,NaN,NaN
28,BALTIMORE,24 inch bins,HOWDEN WHITE TYPE,NaN,09/30/2017,180,180.0,MARYLAND,med,NaN,NaN
29,BALTIMORE,24 inch bins,CINDERELLA,NaN,06/03/2017,380,380.0,NaN,xlge,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
27,PHILADELPHIA,36 inch bins,HOWDEN TYPE,NaN,09/30/2017,140,140.0,DELAWARE,med,NaN,NaN
28,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,NaN,10/15/2016,12,14.0,OHIO,med,NaN,NaN
29,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,NaN,10/22/2016,12,12.0,OHIO,med,NaN,NaN
30,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,NaN,10/29/2016,12,12.0,OHIO,med,NaN,NaN
31,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,NaN,08/26/2017,18,20.0,MICHIGAN,med,NaN,NaN
32,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,NaN,09/16/2017,18,18.0,OHIO,med,NaN,NaN
33,PHILADELPHIA,1 1/9 bushel cartons,PIE TYPE,NaN,09/23/2017,18,22.0,OHIO,med,NaN,NaN
34,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,10/01/2016,250,250.0,PENNSYLVANIA,med,NaN,NaN
35,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,10/15/2016,140,140.0,PENNSYLVANIA,med,NaN,NaN
36,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,10/22/2016,140,150.0,PENNSYLVANIA,med,NaN,NaN
37,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,10/22/2016,75,100.0,PENNSYLVANIA,sml,NaN,NaN
38,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,10/29/2016,140,150.0,PENNSYLVANIA,med,NaN,NaN
39,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,10/29/2016,75,100.0,PENNSYLVANIA,sml,NaN,NaN
40,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,09/23/2017,180,180.0,DELAWARE,med,NaN,NaN
41,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,09/23/2017,140,140.0,DELAWARE,sml,NaN,NaN
42,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,09/23/2017,180,180.0,NEW YORK,med,NaN,NaN
43,PHILADELPHIA,24 inch bins,PIE TYPE,NaN,09/30/2017,140,140.0,DELAWARE,sml,NaN,NaN
44,PHILADELPHIA,24 inch bins,KNUCKLE HEAD,NaN,10/08/2016,210,210.0,NEW JERSEY,med,NaN,NaN
45,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,09/24/2016,17,18.0,OHIO,NaN,NaN,SHELLACKED
46,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,10/01/2016,18,18.0,NEW JERSEY,NaN,NaN,NaN
47,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,10/01/2016,17,18.0,OHIO,NaN,NaN,SHELLACKED
48,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,10/08/2016,15,15.0,OHIO,NaN,NaN,SHELLACKED
49,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,10/15/2016,15,18.0,OHIO,NaN,NaN,SHELLACKED
50,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,10/22/2016,16,18.0,OHIO,NaN,NaN,SHELLACKED
51,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,10/29/2016,16,18.0,OHIO,NaN,NaN,SHELLACKED
52,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,11/05/2016,16,18.0,OHIO,NaN,NaN,SHELLACKED
53,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,08/26/2017,18,20.0,MICHIGAN,NaN,NaN,SHELLACKED
54,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,09/16/2017,16,16.0,OHIO,NaN,NaN,SHELLACKED
55,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,09/23/2017,15,16.0,OHIO,NaN,NaN,SHELLACKED
56,PHILADELPHIA,1/2 bushel cartons,MINIATURE,FLAT TYPE,09/30/2017,15,18.0,OHIO,NaN,NaN,SHELLACKED

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of unit of sale in the Northeast region? In the last lesson, we learned that a unit of sale could be something like a bin or individually. 
2. What is the average number of pumpkins for each variety that came into terminal markets for the year by region? Pumpkin varieties include Howden and Fairytale pumpkins.

In [15]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
northeast_unitofsale_groupby = northeast.groupby('Unit of Sale').agg('mean')
northeast_unitofsale_groupby

               Low Price  High Price
Unit of Sale
EACH           47.916667   59.166667
PER BIN       185.845070  206.619718
SHELLACKED     16.000000   17.545455

In [16]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
northeast_variety_groupby = northeast.groupby('Variety').agg('mean')
northeast_variety_groupby

                           Low Price  High Price
Variety
BIG MACK TYPE             129.454545  147.272727
BLUE TYPE                 260.000000  285.000000
CINDERELLA                206.051282  220.974359
FAIRYTALE                 198.783784  214.108108
HOWDEN TYPE               152.834821  177.098214
HOWDEN WHITE TYPE         170.000000  180.000000
KNUCKLE HEAD              238.888889  260.555556
MINIATURE                  16.391753   17.886598
MIXED HEIRLOOM VARIETIES  210.000000  230.000000
PIE TYPE                  133.404040  148.118687

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!